### ISSUE TITLE
Zone documentation is incomplete / inaccurate

### ISSUE THREAD

**Issue by jonstelly** [JetBrains/resharper-devguide#20]
The zone documentation is insufficient for getting a component loading.  It references a [Zone] attribute that I think was replaced with [ZoneMarker], guessing that happened between EAP and Release?

Also, even with those changes, it's unclear what I need to implement for a zone... I've tried many different options and simply cannot get my extension to simply instantiate my ShellComponent.

**Comment by citizenmatt** [comment]
I've updated the usage docs to indicate that the attribute is called `[ZoneMarker]`, how to implement a class marker, and the name of the namespace marker. I've created issue #24 to track updating the zones "how-to" page.
