### ISSUE TITLE
Cant uninstall platform

### ISSUE THREAD

**Issue by eriksundberg** [JetBrains/resharper-devguide#31]
Visual Studio 2013 was using Resharper 8, wanted dotTrace.

Accidentally installed dotTrace 6, the web installer removed Resharper 8 (could not disable removal). Spent one full morning trying to uninstall ResharperPlatform so I could get Resharper 8 to work again. 

Tried to uninstall program (its not there) tried to manage Extensions in visual studio, unable to remove it from there (uinstall button is enabled but doesnt do anything). Tried to manually hack files to remove it from loading. No luck.

Only thing left is to do a complete uninstall of Visual Studio. 

Very unhappy and annoyed by this complete waste of time.

**Comment by citizenmatt** [comment]
Sorry to hear that. dotTrace requires the common ReSharper Platform, and that can't be installed side-by-side with ReSharper 8.

This repo is for documenting the SDK to extend ReSharper, rather than general support. You can email support@jetbrains.com or raise an issue on https://youtrack.jetbrains.com, and support can address your issues.

**Comment by michalmikee** [comment]
I have the same issue, I have found any solution to this problem?

**Comment by citizenmatt** [comment]
Your best bet is to contact support - this is a repo for the documentation of the SDK, and not a good place for product support (we can't track anything here, or get you in touch with the right people - I can't even redirect you to the right person now). Please email support@jetbrains.com, or raise an issue at https://youtrack.jetbrains.com.

**Comment by alex-hottabych** [comment]
Guys, if anyone experiences a problem with uninstalling JB ReSharper Platform from Visual Studio to install a previous version of JB tools, please refer to http://resharper-support.jetbrains.com/entries/92672788-Uninstalling-new-NET-Tools-from-Visual-Studio

**Comment by logikonline** [comment]
I am stuck in this same hell :(

**Comment by citizenmatt** [comment]
Please contact support@jetbrains.com, or see the link above.
