### ISSUE TITLE
Project Model documentation

### ISSUE THREAD

**Issue by jozefizso** [JetBrains/resharper-devguide#54]
Can you write documentation how to create custom Project Model?

We want to process WiX Setup projects (.wixproj) in ReSharper extension.

**Comment by jozefizso** [comment]
@citizenmatt bump...

**Comment by citizenmatt** [comment]
What is it that you want to do? Provide ReSharper-y goodness for wixprow's .xml files?

**Comment by jozefizso** [comment]
One of my goals was to provide custom icons for WiX Setup project using ReSharper plugin.

The other more important was to improve IntelliSense a bit, eg. provider `!var` and `!bind` completion.

**Comment by citizenmatt** [comment]
I'm afraid I don't know much about .wixproj projects - what are `!var` and `!bind` and what completion would you add? When you say you want icons, where would they be? And finally, do the Wix .xml files already have any ReSharper analysis (do they have the green tick in the top right, for example)?
