### ISSUE TITLE
Ironpython+PyUnit 

### ISSUE THREAD

**Issue by mbparsa** [JetBrains/resharper-devguide#56]
It does not discover unit test written in IronPython, it would be really nice if we could use it for PyUnit coverage etc

**Comment by citizenmatt** [comment]
ReSharper doesn't have any support for Python - you can always add a feature request on [the issue tracker](https://youtrack.jetbrains.com/newIssue?project=RSRP&clearDraft=true&c=).

This repo is to track issues with the development guide for writing ReSharper plugins, so I'm going to close this.

Thanks!
