### ISSUE TITLE
[Custom plugin] How to update all deps e.g. from 2017.1.2 to 2017.2 EAP1

### ISSUE THREAD

**Issue by DoCode** [JetBrains/resharper-devguide#59]
How to update the NuGet dependencies from one version to the next?  
Always when I do this the Package Manager shows many conflicts and nothing happened.  
What is the recommended way to do this?

**Comment by citizenmatt** [comment]
You should be able to just update. What errors do you see?

One issue is that one of the recent SDKs (away from laptop, so can't check) bumped from .net 4 to .net 4.5 - you'll need to set the project to .net 4.5 now.
