### ISSUE TITLE
Recommended version of .NET Framework

### ISSUE THREAD

**Issue by olsh** [JetBrains/resharper-devguide#65]
https://www.jetbrains.com/help/resharper/sdk/Extensions/Plugins/ProjectSetup/CreatingProjects.html

The page says:

> the project should be a class library that targets .NET Framework 4.5

But starting from 2018.2.0, I can't install the SDK on a project that targets 4.5, because of this error:

`
Package JetBrains.NuGet.Frameworks 4.7.0.20180704 is not compatible with net45 (.NETFramework,Version=v4.5). Package JetBrains.NuGet.Frameworks 4.7.0.20180704 supports: net46 (.NETFramework,Version=v4.6)`

Should the doc be updated?

**Comment by matkoch** [comment]
Yes, this should be updated. Thanks for the notice. Will update it shortly )

We will very soon also release a solution template for getting started with ReSharper/Rider plugins. (In case you're interested)
