### ISSUE TITLE
Document ReSharper 2018.3 SDK

### ISSUE THREAD

**Issue by jozefizso** [JetBrains/resharper-devguide#66]

**Comment by matkoch** [comment]
Please elaborate

**Comment by jozefizso** [comment]
Write documentation for the ReSharper 2018.3 SDK

**Comment by matkoch** [comment]
The main parts are documented at https://www.jetbrains.com/help/resharper/sdk/README.html which I assume you already know. If you miss a specific part, then please explain what it is you're looking for.

**Comment by jozefizso** [comment]
That guide is written for ReSharper 8, and has not been updated to ReSharper 9 or the ReSharper Platform.

**Comment by matkoch** [comment]
Which part you think is outdated?

**Comment by jozefizso** [comment]
How do I know when it is not documented?

**Comment by matkoch** [comment]
The documentation has been updated continuously ever since (see https://www.jetbrains.com/help/resharper/sdk/recently_updated.html). ReSharper and Rider are extensible in many ways, which makes it unfeasible to document every bit. Again, if you explain what you're looking for, I probably can help.
