### ISSUE TITLE
Visual Studio F5 experience broken

### ISSUE THREAD

**Issue by maartenba** [JetBrains/resharper-devguide#68]
From https://blog.jetbrains.com/dotnet/2019/02/14/writing-plugins-resharper-rider/#comment-547740:

> Previously (for VS2015 as I was writing my plugin then; I’m porting it for VS2017 now) it was way easier as I just could press F5 key and it was automatically deployed into the test version of VS so I could easily test it (and probably even edit-and-continue, not sure about this).
> Now it’s way harder and practically, it’s broken:
> 1. It’s required to manually install ReSharper into a special VS hive.
> 2. It’s required to manually pack the plugin into a NuGet package and setup ReSharper to use the path where this NuGet package is located. Then launch the VS from test hive and install the ReSharper plugin there.
> 3. It’s possible to setup C# project for ReSharper plugin to deploy updated binaries into ReSharper installation folder (for the test hive). Then on F5 build, it will deploy the updated DLL – but for some reason, it doesn’t deploy PDB file (which is necessary for debugging). So it’s easier to manually copy DLL and PDB files.

**Comment by matkoch** [comment]
@aienabled I've already sent you a mail but got no reply. Could you please elaborate based on the [blog post](https://blog.jetbrains.com/dotnet/2019/02/14/writing-plugins-resharper-rider/) I had written?

**Comment by aienabled** [comment]
@matkoch sorry for the late reply. I'm on a deadline for my project on which I've spent 4 years of my everyday life (gamedev is hard) and I totally missed checking my personal email.

Please just ensure that it works flawlessly with VS now.
My experience was very frustrating in the week prior to your blog post. When I saw the new blog post, I've read it quickly and made a conclusion there are no serious improvements regarding VS but only for Rider. I just expressed my overall feeling about the issues I had during that week when I've tried to update my ReSharper extension to VS2017.  I remember very well that it was way better in VS2015 times and I wish it will be as close to it as possible.
It's your job to ensure it works this way. If it does now, you can dismiss my complaints and close the created Github issues. Alas, I'm very limited in my free time to review the changes and confirm the improvements, but I will be definitely happy to hear back that it works perfectly in VS2017 and/or upcoming VS2019 same as in good old V2015 days.

Regards!

**Comment by matkoch** [comment]
As already mentioned, the plugin template improves the setup situation.
