### ISSUE TITLE
F12 stop working

### ISSUE THREAD

**Issue by mbiesiad** [JetBrains/resharper-devguide#78]
Hi, please take a look on topics like this one (Resharper, VS): 
https://stackoverflow.com/questions/955193/f12-no-longer-works-in-visual-studio/60119990?noredirect=1
unfortunately not always working (asked from ~10y to nowadays).
Best regards

**Comment by mbiesiad** [comment]
Looks inactive (see the dates), closed.

**Comment by matkoch** [comment]
@mbiesiad sorry I missed that. This repository is not meant for issues with ReSharper, but with the ReSharper SDK. As for the broken `GotoDeclaration` action, it's better to file an issue on https://youtrack.jetbrains.com ... I personally can't reproduce the issue, so I guess we they'll ask you for more information.

**Comment by mbiesiad** [comment]
It's OK, thank you for your message.
