### ISSUE TITLE
Question: Possible typo in SDK class name.

### ISSUE THREAD

**Issue by karpovv-boris** [JetBrains/resharper-devguide#82]
Not sure where I can submit this case. Maybe somebody who know could pass it.
Is it typo?

`JetBrains.Application.UI.Actions.MenuGroups.*`

![photo_2021-03-12_07-01-48](https://user-images.githubusercontent.com/78983523/110890315-d7e0ba80-8300-11eb-87d3-e9ea1f902762.jpg)

**Comment by matkoch** [comment]
Sorry for the late response. I actually already forwarded it before. There probably isn't a right place for this kind of things, but thanks anyways for noticing!:)

**Comment by karpovv-boris** [comment]
Alrighty, thanks for your response
