### ISSUE TITLE
Visual studio doesn't recognize Resharper

### ISSUE THREAD

**Issue by miladahmadi33** [JetBrains/resharper-devguide#87]
I installed Resharper `JetBrains.dotUltimate.2021.3.EAP10.Checked` but My Visual studio 2022 `17.0.1` doesn't recognize that.

**Comment by matkoch** [comment]
@miladahmadi33 sorry this slipped through. Are you still facing this issue? Are you using the [plugin template](https://github.com/jetbrains/resharper-rider-plugin) ?
